In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
Financial_Hardships = pd.read_csv("Raw_Datasets/Finacial hardships.csv")

In [3]:
print(Financial_Hardships.head())

       STRUCTURE              STRUCTURE_ID ACTION FREQ REF_AREA INDICATOR  \
0  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      DOM  UHC_FH40
1  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      SRB  UHC_FH40
2  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      GRC  UHC_FH40
3  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      DOM  UHC_FH40
4  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      PSE  UHC_FH40

  URBANIZATION HH_MAC IC_QUINTILE FINANCIAL_HARDSHIP  ...  2015  2016  2017  \
0          URB     _T          _T             ALL_FH  ...   NaN   NaN   NaN
1           _T     _T          _T             PUSHED  ...  0.79  0.70  1.23
2           _T     _T          _T             PUSHED  ...  1.69  2.08  1.34
3           _T     _T       IC_Q1             ALL_FH  ...   NaN   NaN   NaN
4           _T     _T          _T              LARGE  ...   NaN  3.72   NaN

    2018  2019  2020  2021  2022  2023 2024
0  14.17   NaN   NaN   NaN   NaN   NaN  NaN
1   0.81  0.83   NaN  0.79  1.65   NaN  NaN
2   2.11  1.53  1.74  1.87  1.34  1.97  NaN
3  57.49   NaN   NaN   NaN   NaN   NaN  NaN
4    NaN   NaN   NaN   NaN   NaN  3.52  NaN

[5 rows x 74 columns]

In [4]:
print(Financial_Hardships.shape)

(2612, 74)

In [5]:
print(Financial_Hardships.columns)

Index(['STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'REF_AREA', 'INDICATOR',
       'URBANIZATION', 'HH_MAC', 'IC_QUINTILE', 'FINANCIAL_HARDSHIP',
       'INDEX_COMP', 'SPEND_LEVEL', 'UNIT_MEASURE', 'OBS_CONF', 'UNIT_TYPE',
       'DATABASE_ID', 'DECIMALS', 'UNIT_MULT', 'OBS_STATUS', 'FREQ_LABEL',
       'REF_AREA_LABEL', 'INDICATOR_LABEL', 'URBANIZATION_LABEL',
       'HH_MAC_LABEL', 'IC_QUINTILE_LABEL', 'FINANCIAL_HARDSHIP_LABEL',
       'INDEX_COMP_LABEL', 'SPEND_LEVEL_LABEL', 'UNIT_MEASURE_LABEL',
       'OBS_STATUS_LABEL', 'OBS_CONF_LABEL', 'UNIT_TYPE_LABEL',
       'DATABASE_ID_LABEL', 'DECIMALS_LABEL', 'UNIT_MULT_LABEL', '1985',
       '1986', '1987', '1988', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024'],
      dtype='object')

In [6]:
print(Financial_Hardships.info())
print(Financial_Hardships.isnull().sum())
print(Financial_Hardships.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2612 entries, 0 to 2611
Data columns (total 74 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   STRUCTURE                 2612 non-null   object
 1   STRUCTURE_ID              2612 non-null   object
 2   ACTION                    2612 non-null   object
 3   FREQ                      2612 non-null   object
 4   REF_AREA                  2612 non-null   object
 5   INDICATOR                 2612 non-null   object
 6   URBANIZATION              2612 non-null   object
 7   HH_MAC                    2612 non-null   object
 8   IC_QUINTILE               2612 non-null   object
 9   FINANCIAL_HARDSHIP        2612 non-null   object
 10  INDEX_COMP                2612 non-null   object
 11  SPEND_LEVEL               2612 non-null   object
 12  UNIT_MEASURE              2612 non-null   object
 13  OBS_CONF                  2612 non-null   object
 14  UNIT_TYPE                 2612 non-null   object
 15  DATABASE_ID               2612 non-null   object
 16  DECIMALS                  2612 non-null   int64
 17  UNIT_MULT                 2612 non-null   int64
 18  OBS_STATUS                2612 non-null   object
 19  FREQ_LABEL                2612 non-null   object
 20  REF_AREA_LABEL            2612 non-null   object
 21  INDICATOR_LABEL           2612 non-null   object
 22  URBANIZATION_LABEL        2612 non-null   object
 23  HH_MAC_LABEL              2612 non-null   object
 24  IC_QUINTILE_LABEL         2612 non-null   object
 25  FINANCIAL_HARDSHIP_LABEL  2612 non-null   object
 26  INDEX_COMP_LABEL          2612 non-null   object
 27  SPEND_LEVEL_LABEL         2612 non-null   object
 28  UNIT_MEASURE_LABEL        2612 non-null   object
 29  OBS_STATUS_LABEL          2612 non-null   object
 30  OBS_CONF_LABEL            2612 non-null   object
 31  UNIT_TYPE_LABEL           2612 non-null   object
 32  DATABASE_ID_LABEL         2612 non-null   object
 33  DECIMALS_LABEL            2612 non-null   object
 34  UNIT_MULT_LABEL           2612 non-null   object
 35  1985                      10 non-null     float64
 36  1986                      10 non-null     float64
 37  1987                      10 non-null     float64
 38  1988                      12 non-null     float64
 39  1990                      35 non-null     float64
 40  1991                      33 non-null     float64
 41  1992                      58 non-null     float64
 42  1993                      58 non-null     float64
 43  1994                      38 non-null     float64
 44  1995                      101 non-null    float64
 45  1996                      141 non-null    float64
 46  1997                      178 non-null    float64
 47  1998                      275 non-null    float64
 48  1999                      273 non-null    float64
 49  2000                      538 non-null    float64
 50  2001                      472 non-null    float64
 51  2002                      663 non-null    float64
 52  2003                      646 non-null    float64
 53  2004                      676 non-null    float64
 54  2005                      790 non-null    float64
 55  2006                      726 non-null    float64
 56  2007                      705 non-null    float64
 57  2008                      702 non-null    float64
 58  2009                      836 non-null    float64
 59  2010                      878 non-null    float64
 60  2011                      754 non-null    float64
 61  2012                      831 non-null    float64
 62  2013                      691 non-null    float64
 63  2014                      757 non-null    float64
 64  2015                      882 non-null    float64
 65  2016                      858 non-null    float64
 66  2017                      630 non-null    float64
 67  2018                      814 non-null    float64
 68  2019                      635 non-null    float64
 69  2020                      419 non-null    float64
 70  2021                      682 non-null    float64
 71  2022                      544 non-null    float64
 72  2023                      247 non-null    float64
 73  2024                      26 non-null     float64
dtypes: float64(39), int64(2), object(33)
memory usage: 1.5+ MB
None
STRUCTURE          0
STRUCTURE_ID       0
ACTION             0
FREQ               0
REF_AREA           0
                ...
2020            2193
2021            1930
2022            2068
2023            2365
2024            2586
Length: 74, dtype: int64
(2612, 74)

In [7]:
cols_to_keep = ['REF_AREA_LABEL','URBANIZATION_LABEL','HH_MAC_LABEL','IC_QUINTILE_LABEL','FINANCIAL_HARDSHIP', 'INDICATOR_LABEL'] + \
               [col for col in Financial_Hardships.columns if col.isdigit()]

Financial_Hardships = Financial_Hardships[cols_to_keep]

In [8]:
Financial_Hardships.head(10)

,REF_AREA_LABEL,URBANIZATION_LABEL,HH_MAC_LABEL,IC_QUINTILE_LABEL,FINANCIAL_HARDSHIP,INDICATOR_LABEL,1985,1986,1987,1988,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Dominican Republic,Urban area,All types,All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,14.17,NaN,NaN,NaN,NaN,NaN,NaN
1,Serbia,Total,All types,All,PUSHED,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,0.79,0.70,1.23,0.81,0.83,NaN,0.79,1.65,NaN,NaN
2,Greece,Total,All types,All,PUSHED,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,1.69,2.08,1.34,2.11,1.53,1.74,1.87,1.34,1.97,NaN
3,Dominican Republic,Total,All types,Wealth quintile 1 (poorest),ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,57.49,NaN,NaN,NaN,NaN,NaN,NaN
4,West Bank and Gaza,Total,All types,All,LARGE,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,3.72,NaN,NaN,NaN,NaN,NaN,NaN,3.52,NaN
5,Ethiopia,Total,All types,All,FURTHER,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,22.73,NaN,NaN,18.84,NaN,NaN,22.27,NaN,NaN,NaN
6,Brazil,Total,Older adults only,All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Iraq,Total,"Adults, children, and adolescents",All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,32.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Togo,Total,Adults only,All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,27.98,NaN,NaN,NaN,NaN,NaN,3.49,NaN,NaN,NaN
9,Lower middle income,Total,All types,Wealth quintile 5 (richest),ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,5.12,5.19,4.74,4.54,4.54,3.96,3.99,4.52,NaN,NaN

In [9]:
year_cols = [col for col in Financial_Hardships.columns if col.isdigit()]
Financial_Hardships[year_cols].isnull().mean()*100

1985    99.617152
1986    99.617152
1987    99.617152
1988    99.540582
1990    98.660031
1991    98.736600
1992    97.779479
1993    97.779479
1994    98.545176
1995    96.133231
1996    94.601838
1997    93.185299
1998    89.471669
1999    89.548239
2000    79.402757
2001    81.929556
2002    74.617152
2003    75.267994
2004    74.119449
2005    69.754977
2006    72.205207
2007    73.009188
2008    73.124043
2009    67.993874
2010    66.385911
2011    71.133231
2012    68.185299
2013    73.545176
2014    71.018377
2015    66.232772
2016    67.151608
2017    75.880551
2018    68.836141
2019    75.689127
2020    83.958652
2021    73.889740
2022    79.173047
2023    90.543645
2024    99.004594
dtype: float64

In [10]:
cols_to_drop = [str(year) for year in range(1985, 2000)]
Financial_Hardships.drop(columns=cols_to_drop, inplace=True,errors='ignore')

In [11]:
Financial_Hardships.head(10)

,REF_AREA_LABEL,URBANIZATION_LABEL,HH_MAC_LABEL,IC_QUINTILE_LABEL,FINANCIAL_HARDSHIP,INDICATOR_LABEL,2000,2001,2002,2003,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Dominican Republic,Urban area,All types,All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,14.17,NaN,NaN,NaN,NaN,NaN,NaN
1,Serbia,Total,All types,All,PUSHED,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,0.79,0.70,1.23,0.81,0.83,NaN,0.79,1.65,NaN,NaN
2,Greece,Total,All types,All,PUSHED,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,1.69,2.08,1.34,2.11,1.53,1.74,1.87,1.34,1.97,NaN
3,Dominican Republic,Total,All types,Wealth quintile 1 (poorest),ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,57.49,NaN,NaN,NaN,NaN,NaN,NaN
4,West Bank and Gaza,Total,All types,All,LARGE,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,3.72,NaN,NaN,NaN,NaN,NaN,NaN,3.52,NaN
5,Ethiopia,Total,All types,All,FURTHER,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,22.73,NaN,NaN,18.84,NaN,NaN,22.27,NaN,NaN,NaN
6,Brazil,Total,Older adults only,All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Iraq,Total,"Adults, children, and adolescents",All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,32.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Togo,Total,Adults only,All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,27.98,NaN,NaN,NaN,NaN,NaN,3.49,NaN,NaN,NaN
9,Lower middle income,Total,All types,Wealth quintile 5 (richest),ALL_FH,Population facing financial hardship due to ou...,3.52,3.3,3.97,3.36,...,5.12,5.19,4.74,4.54,4.54,3.96,3.99,4.52,NaN,NaN

In [12]:
Financial_Hardships.columns

Index(['REF_AREA_LABEL', 'URBANIZATION_LABEL', 'HH_MAC_LABEL',
       'IC_QUINTILE_LABEL', 'FINANCIAL_HARDSHIP', 'INDICATOR_LABEL', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022', '2023', '2024'],
      dtype='object')

In [13]:
year_cols = [col for col in Financial_Hardships.columns if col.isdigit()]

# check how many countries you lose at 70% threshold
row_missing_pct = Financial_Hardships[year_cols].isnull().mean(axis=1) * 100

print("Before:", Financial_Hardships.shape[0], "rows")
print("Dropped:", (row_missing_pct > 70).sum(), "rows")
print("Kept:", (row_missing_pct <= 70).sum(), "rows")

Before: 2612 rows
Dropped: 1911 rows
Kept: 701 rows

In [14]:
print("Before:", Financial_Hardships.shape[0], "rows")
print("Dropped:", (row_missing_pct > 80).sum(), "rows")
print("Kept:", (row_missing_pct <= 80).sum(), "rows")

Before: 2612 rows
Dropped: 1572 rows
Kept: 1040 rows

In [15]:
Financial_Hardships = Financial_Hardships[row_missing_pct <= 80]
print("New shape:", Financial_Hardships.shape)

New shape: (1040, 31)

In [16]:
Financial_Hardships['REF_AREA_LABEL'].nunique()

81

In [17]:
# reload
Financial_Hardships = pd.read_csv("/Users/deannalakshman/Desktop/IIT/YEAR 2/SEM 2/DSPLC/Individual technical/Raw_Datasets/Finacial hardships.csv")

# drop 1985-1999 year columns
cols_to_drop = [str(year) for year in range(1985, 2000)]
Financial_Hardships.drop(columns=cols_to_drop, inplace=True, errors='ignore')

# keep only the columns you need
cols_to_keep = ['REF_AREA_LABEL', 'FINANCIAL_HARDSHIP_LABEL', 'URBANIZATION_LABEL', 
                'IC_QUINTILE_LABEL', 'INDICATOR_LABEL'] + \
               [col for col in Financial_Hardships.columns if col.isdigit()]

Financial_Hardships = Financial_Hardships[cols_to_keep]

# remove regional aggregates
regions_to_remove = [
    'East Asia & Pacific', 'Europe & Central Asia', 'World',
    'High income', 'Latin America & Caribbean', 'Low income',
    'Lower middle income', 'Middle East, North Africa, Afghanistan & Pakistan',
    'North America', 'South Asia', 'Sub-Saharan Africa', 'Upper middle income'
]
Financial_Hardships = Financial_Hardships[~Financial_Hardships['REF_AREA_LABEL'].isin(regions_to_remove)]

print(Financial_Hardships.shape)
Financial_Hardships.head()

(2492, 30)

,REF_AREA_LABEL,FINANCIAL_HARDSHIP_LABEL,URBANIZATION_LABEL,IC_QUINTILE_LABEL,INDICATOR_LABEL,2000,2001,2002,2003,2004,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Dominican Republic,All financial hardship,Urban area,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,14.17,NaN,NaN,NaN,NaN,NaN,NaN
1,Serbia,2.1: Pushed into poverty (based on societal po...,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,0.79,0.70,1.23,0.81,0.83,NaN,0.79,1.65,NaN,NaN
2,Greece,2.1: Pushed into poverty (based on societal po...,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,2.15,...,1.69,2.08,1.34,2.11,1.53,1.74,1.87,1.34,1.97,NaN
3,Dominican Republic,All financial hardship,Total,Wealth quintile 1 (poorest),Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,57.49,NaN,NaN,NaN,NaN,NaN,NaN
4,West Bank and Gaza,1: Facing large (but non-impoverishing) out-of...,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,4.12,...,NaN,3.72,NaN,NaN,NaN,NaN,NaN,NaN,3.52,NaN

In [18]:
Financial_Hardships.drop(columns=['2024'], inplace=True, errors='ignore')

In [19]:
Financial_Hardships.drop_duplicates(inplace=True)

In [20]:
fh_label_map = {
    'All financial hardship': 'All',
    '1: Facing large (but non-impoverishing) out-of-pocket health expenditure': 'Large OOP',
    '2: Facing impoverishing out-of-pocket health expenditure, based on the societal poverty line': 'Impoverishing',
    '2.1: Pushed into poverty (based on societal poverty line) due to out-of-pocket health expenditure': 'Pushed into poverty',
    '2.2: Further impoverished due to out-of-pocket health expenditure, based on the societal poverty line': 'Further impoverished'
}
Financial_Hardships['FINANCIAL_HARDSHIP_LABEL'] = Financial_Hardships['FINANCIAL_HARDSHIP_LABEL'].map(fh_label_map)

In [23]:
# only drop the 6 countries with 100% missing - they are completely useless
year_cols = [col for col in Financial_Hardships.columns if col.isdigit()]
country_miss = Financial_Hardships.groupby('REF_AREA_LABEL')[year_cols].apply(lambda x: x.isnull().mean().mean() * 100)
countries_to_drop = country_miss[country_miss == 100].index.tolist()
print("Dropping:", countries_to_drop)
Financial_Hardships = Financial_Hardships[~Financial_Hardships['REF_AREA_LABEL'].isin(countries_to_drop)]
print("Remaining shape:", Financial_Hardships.shape)

Dropping: ['Austria', 'Iceland', 'Lebanon', 'Norway', 'Oman', 'Sweden']
Remaining shape: (2426, 29)

In [24]:
Financial_Hardships.to_csv("Cleaned_datasets/Financial_Hardships_Cleaned.csv", index=False, errors='ignore')

In [26]:
print("Saved successfully")
print("Final shape:", Financial_Hardships.shape)
print("Countries remaining:", Financial_Hardships['REF_AREA_LABEL'].nunique())

Saved successfully
Final shape: (2426, 29)
Countries remaining: 162