In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
Health_Coverage = pd.read_csv("Raw_Datasets/Health_coverage.csv")
Financial_Hardships = pd.read_csv("Raw_Datasets/Finacial hardships.csv")

In [3]:
print(Health_Coverage.head())

       STRUCTURE              STRUCTURE_ID ACTION FREQ REF_AREA INDICATOR  \
0  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      KHM   UHC_SCI
1  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      MHL   UHC_SCI
2  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      ESP   UHC_SCI
3  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      BOL   UHC_SCI
4  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      TUN   UHC_SCI

  URBANIZATION HH_MAC IC_QUINTILE FINANCIAL_HARDSHIP  ...  2014  2015  2016  \
0           _Z     _Z          _Z                 _Z  ...  51.0  52.0  55.0
1           _Z     _Z          _Z                 _Z  ...  73.0  74.0  76.0
2           _Z     _Z          _Z                 _Z  ...  98.0  97.0  98.0
3           _Z     _Z          _Z                 _Z  ...  68.0  69.0  69.0
4           _Z     _Z          _Z                 _Z  ...  74.0  76.0  78.0

   2017  2018  2019  2020  2021  2022  2023
0  57.0  56.0  57.0  57.0  59.0  60.0  62.0
1  76.0  73.0  73.0  73.0  74.0  74.0  75.0
2  98.0  94.0  95.0  96.0  93.0  94.0  93.0
3  70.0  70.0  70.0  71.0  71.0  71.0  72.0
4  80.0  82.0  82.0  81.0  81.0  81.0  81.0

[5 rows x 59 columns]

In [4]:
print(Financial_Hardships.head())

       STRUCTURE              STRUCTURE_ID ACTION FREQ REF_AREA INDICATOR  \
0  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      DOM  UHC_FH40
1  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      SRB  UHC_FH40
2  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      GRC  UHC_FH40
3  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      DOM  UHC_FH40
4  datastructure  WB.GGH.HNP:DS_UHC(1.1.0)      I    A      PSE  UHC_FH40

  URBANIZATION HH_MAC IC_QUINTILE FINANCIAL_HARDSHIP  ...  2015  2016  2017  \
0          URB     _T          _T             ALL_FH  ...   NaN   NaN   NaN
1           _T     _T          _T             PUSHED  ...  0.79  0.70  1.23
2           _T     _T          _T             PUSHED  ...  1.69  2.08  1.34
3           _T     _T       IC_Q1             ALL_FH  ...   NaN   NaN   NaN
4           _T     _T          _T              LARGE  ...   NaN  3.72   NaN

    2018  2019  2020  2021  2022  2023 2024
0  14.17   NaN   NaN   NaN   NaN   NaN  NaN
1   0.81  0.83   NaN  0.79  1.65   NaN  NaN
2   2.11  1.53  1.74  1.87  1.34  1.97  NaN
3  57.49   NaN   NaN   NaN   NaN   NaN  NaN
4    NaN   NaN   NaN   NaN   NaN  3.52  NaN

[5 rows x 74 columns]

In [5]:
print(Health_Coverage.shape)

(1035, 59)

In [6]:
print(Financial_Hardships.shape)

(2612, 74)

In [7]:
print(Health_Coverage.columns)

Index(['STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'REF_AREA', 'INDICATOR',
       'URBANIZATION', 'HH_MAC', 'IC_QUINTILE', 'FINANCIAL_HARDSHIP',
       'INDEX_COMP', 'SPEND_LEVEL', 'UNIT_MEASURE', 'OBS_CONF', 'UNIT_TYPE',
       'DATABASE_ID', 'DECIMALS', 'UNIT_MULT', 'OBS_STATUS', 'FREQ_LABEL',
       'REF_AREA_LABEL', 'INDICATOR_LABEL', 'URBANIZATION_LABEL',
       'HH_MAC_LABEL', 'IC_QUINTILE_LABEL', 'FINANCIAL_HARDSHIP_LABEL',
       'INDEX_COMP_LABEL', 'SPEND_LEVEL_LABEL', 'UNIT_MEASURE_LABEL',
       'OBS_STATUS_LABEL', 'OBS_CONF_LABEL', 'UNIT_TYPE_LABEL',
       'DATABASE_ID_LABEL', 'DECIMALS_LABEL', 'UNIT_MULT_LABEL', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022', '2023'],
      dtype='object')

In [8]:
print(Financial_Hardships.columns)

Index(['STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'REF_AREA', 'INDICATOR',
       'URBANIZATION', 'HH_MAC', 'IC_QUINTILE', 'FINANCIAL_HARDSHIP',
       'INDEX_COMP', 'SPEND_LEVEL', 'UNIT_MEASURE', 'OBS_CONF', 'UNIT_TYPE',
       'DATABASE_ID', 'DECIMALS', 'UNIT_MULT', 'OBS_STATUS', 'FREQ_LABEL',
       'REF_AREA_LABEL', 'INDICATOR_LABEL', 'URBANIZATION_LABEL',
       'HH_MAC_LABEL', 'IC_QUINTILE_LABEL', 'FINANCIAL_HARDSHIP_LABEL',
       'INDEX_COMP_LABEL', 'SPEND_LEVEL_LABEL', 'UNIT_MEASURE_LABEL',
       'OBS_STATUS_LABEL', 'OBS_CONF_LABEL', 'UNIT_TYPE_LABEL',
       'DATABASE_ID_LABEL', 'DECIMALS_LABEL', 'UNIT_MULT_LABEL', '1985',
       '1986', '1987', '1988', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024'],
      dtype='object')

In [9]:
print(Health_Coverage.info())
print(Health_Coverage.isnull().sum())
print(Health_Coverage.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 59 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   STRUCTURE                 1035 non-null   object
 1   STRUCTURE_ID              1035 non-null   object
 2   ACTION                    1035 non-null   object
 3   FREQ                      1035 non-null   object
 4   REF_AREA                  1035 non-null   object
 5   INDICATOR                 1035 non-null   object
 6   URBANIZATION              1035 non-null   object
 7   HH_MAC                    1035 non-null   object
 8   IC_QUINTILE               1035 non-null   object
 9   FINANCIAL_HARDSHIP        1035 non-null   object
 10  INDEX_COMP                1035 non-null   object
 11  SPEND_LEVEL               1035 non-null   object
 12  UNIT_MEASURE              1035 non-null   object
 13  OBS_CONF                  1035 non-null   object
 14  UNIT_TYPE                 1035 non-null   object
 15  DATABASE_ID               1035 non-null   object
 16  DECIMALS                  1035 non-null   int64
 17  UNIT_MULT                 1035 non-null   int64
 18  OBS_STATUS                1035 non-null   object
 19  FREQ_LABEL                1035 non-null   object
 20  REF_AREA_LABEL            1035 non-null   object
 21  INDICATOR_LABEL           1035 non-null   object
 22  URBANIZATION_LABEL        1035 non-null   object
 23  HH_MAC_LABEL              1035 non-null   object
 24  IC_QUINTILE_LABEL         1035 non-null   object
 25  FINANCIAL_HARDSHIP_LABEL  1035 non-null   object
 26  INDEX_COMP_LABEL          1035 non-null   object
 27  SPEND_LEVEL_LABEL         1035 non-null   object
 28  UNIT_MEASURE_LABEL        1035 non-null   object
 29  OBS_STATUS_LABEL          1035 non-null   object
 30  OBS_CONF_LABEL            1035 non-null   object
 31  UNIT_TYPE_LABEL           1035 non-null   object
 32  DATABASE_ID_LABEL         1035 non-null   object
 33  DECIMALS_LABEL            1035 non-null   object
 34  UNIT_MULT_LABEL           1035 non-null   object
 35  2000                      1035 non-null   float64
 36  2001                      1035 non-null   float64
 37  2002                      1035 non-null   float64
 38  2003                      1035 non-null   float64
 39  2004                      1035 non-null   float64
 40  2005                      1035 non-null   float64
 41  2006                      1035 non-null   float64
 42  2007                      1035 non-null   float64
 43  2008                      1035 non-null   float64
 44  2009                      1035 non-null   float64
 45  2010                      1035 non-null   float64
 46  2011                      1035 non-null   float64
 47  2012                      1035 non-null   float64
 48  2013                      1035 non-null   float64
 49  2014                      1035 non-null   float64
 50  2015                      1035 non-null   float64
 51  2016                      1035 non-null   float64
 52  2017                      1035 non-null   float64
 53  2018                      1035 non-null   float64
 54  2019                      1035 non-null   float64
 55  2020                      1035 non-null   float64
 56  2021                      1035 non-null   float64
 57  2022                      1035 non-null   float64
 58  2023                      1035 non-null   float64
dtypes: float64(24), int64(2), object(33)
memory usage: 477.2+ KB
None
STRUCTURE                   0
STRUCTURE_ID                0
ACTION                      0
FREQ                        0
REF_AREA                    0
INDICATOR                   0
URBANIZATION                0
HH_MAC                      0
IC_QUINTILE                 0
FINANCIAL_HARDSHIP          0
INDEX_COMP                  0
SPEND_LEVEL                 0
UNIT_MEASURE                0
OBS_CONF                    0
UNIT_TYPE                   0
DATABASE_ID                 0
DECIMALS                    0
UNIT_MULT                   0
OBS_STATUS                  0
FREQ_LABEL                  0
REF_AREA_LABEL              0
INDICATOR_LABEL             0
URBANIZATION_LABEL          0
HH_MAC_LABEL                0
IC_QUINTILE_LABEL           0
FINANCIAL_HARDSHIP_LABEL    0
INDEX_COMP_LABEL            0
SPEND_LEVEL_LABEL           0
UNIT_MEASURE_LABEL          0
OBS_STATUS_LABEL            0
OBS_CONF_LABEL              0
UNIT_TYPE_LABEL             0
DATABASE_ID_LABEL           0
DECIMALS_LABEL              0
UNIT_MULT_LABEL             0
2000                        0
2001                        0
2002                        0
2003                        0
2004                        0
2005                        0
2006                        0
2007                        0
2008                        0
2009                        0
2010                        0
2011                        0
2012                        0
2013                        0
2014                        0
2015                        0
2016                        0
2017                        0
2018                        0
2019                        0
2020                        0
2021                        0
2022                        0
2023                        0
dtype: int64
(1035, 59)

In [10]:
print(Financial_Hardships.info())
print(Financial_Hardships.isnull().sum())
print(Financial_Hardships.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2612 entries, 0 to 2611
Data columns (total 74 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   STRUCTURE                 2612 non-null   object
 1   STRUCTURE_ID              2612 non-null   object
 2   ACTION                    2612 non-null   object
 3   FREQ                      2612 non-null   object
 4   REF_AREA                  2612 non-null   object
 5   INDICATOR                 2612 non-null   object
 6   URBANIZATION              2612 non-null   object
 7   HH_MAC                    2612 non-null   object
 8   IC_QUINTILE               2612 non-null   object
 9   FINANCIAL_HARDSHIP        2612 non-null   object
 10  INDEX_COMP                2612 non-null   object
 11  SPEND_LEVEL               2612 non-null   object
 12  UNIT_MEASURE              2612 non-null   object
 13  OBS_CONF                  2612 non-null   object
 14  UNIT_TYPE                 2612 non-null   object
 15  DATABASE_ID               2612 non-null   object
 16  DECIMALS                  2612 non-null   int64
 17  UNIT_MULT                 2612 non-null   int64
 18  OBS_STATUS                2612 non-null   object
 19  FREQ_LABEL                2612 non-null   object
 20  REF_AREA_LABEL            2612 non-null   object
 21  INDICATOR_LABEL           2612 non-null   object
 22  URBANIZATION_LABEL        2612 non-null   object
 23  HH_MAC_LABEL              2612 non-null   object
 24  IC_QUINTILE_LABEL         2612 non-null   object
 25  FINANCIAL_HARDSHIP_LABEL  2612 non-null   object
 26  INDEX_COMP_LABEL          2612 non-null   object
 27  SPEND_LEVEL_LABEL         2612 non-null   object
 28  UNIT_MEASURE_LABEL        2612 non-null   object
 29  OBS_STATUS_LABEL          2612 non-null   object
 30  OBS_CONF_LABEL            2612 non-null   object
 31  UNIT_TYPE_LABEL           2612 non-null   object
 32  DATABASE_ID_LABEL         2612 non-null   object
 33  DECIMALS_LABEL            2612 non-null   object
 34  UNIT_MULT_LABEL           2612 non-null   object
 35  1985                      10 non-null     float64
 36  1986                      10 non-null     float64
 37  1987                      10 non-null     float64
 38  1988                      12 non-null     float64
 39  1990                      35 non-null     float64
 40  1991                      33 non-null     float64
 41  1992                      58 non-null     float64
 42  1993                      58 non-null     float64
 43  1994                      38 non-null     float64
 44  1995                      101 non-null    float64
 45  1996                      141 non-null    float64
 46  1997                      178 non-null    float64
 47  1998                      275 non-null    float64
 48  1999                      273 non-null    float64
 49  2000                      538 non-null    float64
 50  2001                      472 non-null    float64
 51  2002                      663 non-null    float64
 52  2003                      646 non-null    float64
 53  2004                      676 non-null    float64
 54  2005                      790 non-null    float64
 55  2006                      726 non-null    float64
 56  2007                      705 non-null    float64
 57  2008                      702 non-null    float64
 58  2009                      836 non-null    float64
 59  2010                      878 non-null    float64
 60  2011                      754 non-null    float64
 61  2012                      831 non-null    float64
 62  2013                      691 non-null    float64
 63  2014                      757 non-null    float64
 64  2015                      882 non-null    float64
 65  2016                      858 non-null    float64
 66  2017                      630 non-null    float64
 67  2018                      814 non-null    float64
 68  2019                      635 non-null    float64
 69  2020                      419 non-null    float64
 70  2021                      682 non-null    float64
 71  2022                      544 non-null    float64
 72  2023                      247 non-null    float64
 73  2024                      26 non-null     float64
dtypes: float64(39), int64(2), object(33)
memory usage: 1.5+ MB
None
STRUCTURE          0
STRUCTURE_ID       0
ACTION             0
FREQ               0
REF_AREA           0
                ...
2020            2193
2021            1930
2022            2068
2023            2365
2024            2586
Length: 74, dtype: int64
(2612, 74)

In [11]:
cols_to_keep = ['REF_AREA_LABEL', 'INDEX_COMP_LABEL', 'INDICATOR_LABEL'] + \
               [col for col in Health_Coverage.columns if col.isdigit()]

Health_Coverage = Health_Coverage[cols_to_keep]

In [12]:
Health_Coverage.head(10)

,REF_AREA_LABEL,INDEX_COMP_LABEL,INDICATOR_LABEL,2000,2001,2002,2003,2004,2005,2006,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Cambodia,Full index,Universal health coverage (UHC) service covera...,26.0,27.0,29.0,31.0,33.0,35.0,37.0,...,51.0,52.0,55.0,57.0,56.0,57.0,57.0,59.0,60.0,62.0
1,Marshall Islands,Service capacity and access,Universal health coverage (UHC) service covera...,80.0,80.0,80.0,80.0,80.0,80.0,80.0,...,73.0,74.0,76.0,76.0,73.0,73.0,73.0,74.0,74.0,75.0
2,Spain,Service capacity and access,Universal health coverage (UHC) service covera...,75.0,75.0,75.0,75.0,75.0,75.0,75.0,...,98.0,97.0,98.0,98.0,94.0,95.0,96.0,93.0,94.0,93.0
3,Bolivia,Non-communicable diseases,Universal health coverage (UHC) service covera...,53.0,54.0,56.0,57.0,59.0,60.0,61.0,...,68.0,69.0,69.0,70.0,70.0,70.0,71.0,71.0,71.0,72.0
4,Tunisia,"Reproductive, maternal, newborn, and child health",Universal health coverage (UHC) service covera...,59.0,61.0,62.0,64.0,65.0,66.0,68.0,...,74.0,76.0,78.0,80.0,82.0,82.0,81.0,81.0,81.0,81.0
5,El Salvador,"Reproductive, maternal, newborn, and child health",Universal health coverage (UHC) service covera...,71.0,71.0,71.0,72.0,72.0,73.0,74.0,...,81.0,79.0,79.0,78.0,77.0,77.0,76.0,76.0,76.0,76.0
6,"Gambia, The",Infectious diseases,Universal health coverage (UHC) service covera...,15.0,13.0,13.0,10.0,9.0,18.0,31.0,...,54.0,49.0,40.0,52.0,50.0,48.0,44.0,44.0,55.0,54.0
7,Slovenia,Infectious diseases,Universal health coverage (UHC) service covera...,99.0,99.0,99.0,99.0,99.0,99.0,99.0,...,99.0,99.0,99.0,99.0,98.0,98.0,98.0,98.0,98.0,98.0
8,Costa Rica,Infectious diseases,Universal health coverage (UHC) service covera...,94.0,94.0,94.0,94.0,94.0,95.0,95.0,...,97.0,97.0,97.0,97.0,98.0,98.0,98.0,98.0,98.0,98.0
9,Estonia,Non-communicable diseases,Universal health coverage (UHC) service covera...,31.0,32.0,34.0,35.0,37.0,38.0,39.0,...,48.0,49.0,50.0,50.0,51.0,52.0,53.0,53.0,54.0,55.0

In [13]:
Health_Coverage['REF_AREA_LABEL'].unique()

array(['Cambodia', 'Marshall Islands', 'Spain', 'Bolivia', 'Tunisia',
       'El Salvador', 'Gambia, The', 'Slovenia', 'Costa Rica', 'Estonia',
       'Dominica', 'Morocco', 'Samoa', 'Palau', 'Equatorial Guinea',
       'Central African Republic', 'Zambia', 'Kiribati',
       'Papua New Guinea', 'Chile', 'Nepal', 'Peru', 'Timor-Leste',
       'Maldives', 'Djibouti', 'Ecuador', 'Togo', 'Senegal',
       'Micronesia, Fed. Sts.', 'Türkiye', 'Mexico', 'Yemen, Rep.',
       'Moldova', 'Italy', 'Jordan', 'Kyrgyz Republic', 'Kuwait',
       'South Sudan', 'Russian Federation', 'Singapore', 'Hungary',
       'Australia', 'Congo, Rep.', 'World', 'Antigua and Barbuda',
       'Denmark', 'Dominican Republic', 'Nicaragua', 'Luxembourg',
       'Congo, Dem. Rep.', 'South Asia', 'Lebanon', 'Ireland', 'Poland',
       'Netherlands', 'Niger', 'Azerbaijan', 'Libya', 'Venezuela, RB',
       'Tajikistan', 'Korea, Rep.', 'Botswana', 'Vietnam', 'Liberia',
       'Syrian Arab Republic', 'Upper middle income', 'Belgium',
       'Burundi', 'Sweden', 'Mauritania', 'Latin America & Caribbean',
       'Czechia', 'Ethiopia', 'Jamaica', 'Belize', 'Myanmar', 'Suriname',
       'Paraguay', 'North America', 'Latvia', 'New Zealand',
       'Solomon Islands', 'Brunei Darussalam', 'Cuba', 'Iraq', 'Bahrain',
       'United Arab Emirates', 'Portugal', 'Low income', 'Colombia',
       'Angola', 'Vanuatu', 'Iceland', 'Ukraine', 'Bhutan', 'Rwanda',
       'Malaysia', 'Bahamas, The', 'Eritrea', 'Germany', 'Guinea-Bissau',
       'Ghana', 'Lower middle income', 'Kazakhstan', 'Thailand',
       'North Macedonia', "Korea, Dem. People's Rep.", 'Guinea',
       'Iran, Islamic Rep.', 'Guyana', 'Sri Lanka', 'Mongolia',
       'Bulgaria', 'Chad', 'United Kingdom', 'Croatia', 'France',
       'Tanzania', 'Canada', 'Nigeria', 'Malta', 'China', 'San Marino',
       'Pakistan', 'Côte d’Ivoire', 'Bangladesh', 'Guatemala', 'Nauru',
       'Fiji', 'Indonesia', 'Saudi Arabia', 'Bosnia and Herzegovina',
       'Sudan', 'Grenada', 'Slovak Republic', 'Lao PDR', 'Kenya',
       'Mozambique', 'Algeria', 'Malawi', 'St. Kitts and Nevis', 'Tonga',
       'Georgia', 'St. Lucia', 'Cameroon', 'East Asia & Pacific',
       'Europe & Central Asia', 'Armenia', 'Eswatini', 'Uzbekistan',
       'Haiti', 'Lesotho', 'Sub-Saharan Africa', 'Romania', 'Mali',
       'Gabon', 'Switzerland', 'Niue', 'Argentina', 'Panama', 'Mauritius',
       'Norway', 'Belarus', 'Comoros', 'Cyprus', 'Tuvalu', 'Sierra Leone',
       'Seychelles', 'Andorra', 'Uganda', 'High income', 'United States',
       'St. Vincent and the Grenadines', 'Afghanistan', 'Albania',
       'São Tomé and Príncipe', 'Lithuania', 'Cabo Verde', 'South Africa',
       'Zimbabwe', 'India', 'Burkina Faso', 'Qatar', 'Brazil', 'Monaco',
       'Japan', 'Namibia',
       'Middle East, North Africa, Afghanistan & Pakistan', 'Austria',
       'Montenegro', 'Egypt, Arab Rep.', 'Oman', 'Finland', 'Madagascar',
       'Uruguay', 'Benin', 'Federal Republic of Somalia', 'Cook Islands',
       'Trinidad and Tobago', 'Greece', 'Honduras', 'West Bank and Gaza',
       'Barbados', 'Israel', 'Serbia', 'Philippines', 'Turkmenistan'],
      dtype=object)

In [14]:
regions_to_remove = [
    'East Asia & Pacific',
    'Europe & Central Asia',
    'World',
    'High income',
    'Latin America & Caribbean',
    'Low income',
    'Lower middle income',
    'Middle East, North Africa, Afghanistan & Pakistan',
    'North America',
    'South Asia',
    'Sub-Saharan Africa',
    'Upper middle income'
]

Health_Coverage = Health_Coverage[~Health_Coverage['REF_AREA_LABEL'].isin(regions_to_remove)]

In [15]:
Health_Coverage['REF_AREA_LABEL'].unique()

array(['Cambodia', 'Marshall Islands', 'Spain', 'Bolivia', 'Tunisia',
       'El Salvador', 'Gambia, The', 'Slovenia', 'Costa Rica', 'Estonia',
       'Dominica', 'Morocco', 'Samoa', 'Palau', 'Equatorial Guinea',
       'Central African Republic', 'Zambia', 'Kiribati',
       'Papua New Guinea', 'Chile', 'Nepal', 'Peru', 'Timor-Leste',
       'Maldives', 'Djibouti', 'Ecuador', 'Togo', 'Senegal',
       'Micronesia, Fed. Sts.', 'Türkiye', 'Mexico', 'Yemen, Rep.',
       'Moldova', 'Italy', 'Jordan', 'Kyrgyz Republic', 'Kuwait',
       'South Sudan', 'Russian Federation', 'Singapore', 'Hungary',
       'Australia', 'Congo, Rep.', 'Antigua and Barbuda', 'Denmark',
       'Dominican Republic', 'Nicaragua', 'Luxembourg',
       'Congo, Dem. Rep.', 'Lebanon', 'Ireland', 'Poland', 'Netherlands',
       'Niger', 'Azerbaijan', 'Libya', 'Venezuela, RB', 'Tajikistan',
       'Korea, Rep.', 'Botswana', 'Vietnam', 'Liberia',
       'Syrian Arab Republic', 'Belgium', 'Burundi', 'Sweden',
       'Mauritania', 'Czechia', 'Ethiopia', 'Jamaica', 'Belize',
       'Myanmar', 'Suriname', 'Paraguay', 'Latvia', 'New Zealand',
       'Solomon Islands', 'Brunei Darussalam', 'Cuba', 'Iraq', 'Bahrain',
       'United Arab Emirates', 'Portugal', 'Colombia', 'Angola',
       'Vanuatu', 'Iceland', 'Ukraine', 'Bhutan', 'Rwanda', 'Malaysia',
       'Bahamas, The', 'Eritrea', 'Germany', 'Guinea-Bissau', 'Ghana',
       'Kazakhstan', 'Thailand', 'North Macedonia',
       "Korea, Dem. People's Rep.", 'Guinea', 'Iran, Islamic Rep.',
       'Guyana', 'Sri Lanka', 'Mongolia', 'Bulgaria', 'Chad',
       'United Kingdom', 'Croatia', 'France', 'Tanzania', 'Canada',
       'Nigeria', 'Malta', 'China', 'San Marino', 'Pakistan',
       'Côte d’Ivoire', 'Bangladesh', 'Guatemala', 'Nauru', 'Fiji',
       'Indonesia', 'Saudi Arabia', 'Bosnia and Herzegovina', 'Sudan',
       'Grenada', 'Slovak Republic', 'Lao PDR', 'Kenya', 'Mozambique',
       'Algeria', 'Malawi', 'St. Kitts and Nevis', 'Tonga', 'Georgia',
       'St. Lucia', 'Cameroon', 'Armenia', 'Eswatini', 'Uzbekistan',
       'Haiti', 'Lesotho', 'Romania', 'Mali', 'Gabon', 'Switzerland',
       'Niue', 'Argentina', 'Panama', 'Mauritius', 'Norway', 'Belarus',
       'Comoros', 'Cyprus', 'Tuvalu', 'Sierra Leone', 'Seychelles',
       'Andorra', 'Uganda', 'United States',
       'St. Vincent and the Grenadines', 'Afghanistan', 'Albania',
       'São Tomé and Príncipe', 'Lithuania', 'Cabo Verde', 'South Africa',
       'Zimbabwe', 'India', 'Burkina Faso', 'Qatar', 'Brazil', 'Monaco',
       'Japan', 'Namibia', 'Austria', 'Montenegro', 'Egypt, Arab Rep.',
       'Oman', 'Finland', 'Madagascar', 'Uruguay', 'Benin',
       'Federal Republic of Somalia', 'Cook Islands',
       'Trinidad and Tobago', 'Greece', 'Honduras', 'West Bank and Gaza',
       'Barbados', 'Israel', 'Serbia', 'Philippines', 'Turkmenistan'],
      dtype=object)

In [16]:
Health_Coverage['REF_AREA_LABEL'].nunique()

195

In [17]:
cols_to_keep = ['REF_AREA_LABEL','URBANIZATION_LABEL','HH_MAC_LABEL','IC_QUINTILE_LABEL','FINANCIAL_HARDSHIP', 'INDICATOR_LABEL'] + \
               [col for col in Financial_Hardships.columns if col.isdigit()]

Financial_Hardships = Financial_Hardships[cols_to_keep]

In [18]:
Financial_Hardships.head(10)

,REF_AREA_LABEL,URBANIZATION_LABEL,HH_MAC_LABEL,IC_QUINTILE_LABEL,FINANCIAL_HARDSHIP,INDICATOR_LABEL,1985,1986,1987,1988,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Dominican Republic,Urban area,All types,All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,14.17,NaN,NaN,NaN,NaN,NaN,NaN
1,Serbia,Total,All types,All,PUSHED,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,0.79,0.70,1.23,0.81,0.83,NaN,0.79,1.65,NaN,NaN
2,Greece,Total,All types,All,PUSHED,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,1.69,2.08,1.34,2.11,1.53,1.74,1.87,1.34,1.97,NaN
3,Dominican Republic,Total,All types,Wealth quintile 1 (poorest),ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,57.49,NaN,NaN,NaN,NaN,NaN,NaN
4,West Bank and Gaza,Total,All types,All,LARGE,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,3.72,NaN,NaN,NaN,NaN,NaN,NaN,3.52,NaN
5,Ethiopia,Total,All types,All,FURTHER,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,22.73,NaN,NaN,18.84,NaN,NaN,22.27,NaN,NaN,NaN
6,Brazil,Total,Older adults only,All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Iraq,Total,"Adults, children, and adolescents",All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,32.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Togo,Total,Adults only,All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,27.98,NaN,NaN,NaN,NaN,NaN,3.49,NaN,NaN,NaN
9,Lower middle income,Total,All types,Wealth quintile 5 (richest),ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,5.12,5.19,4.74,4.54,4.54,3.96,3.99,4.52,NaN,NaN

In [19]:
year_cols = [col for col in Financial_Hardships.columns if col.isdigit()]
Financial_Hardships[year_cols].isnull().mean()*100

1985    99.617152
1986    99.617152
1987    99.617152
1988    99.540582
1990    98.660031
1991    98.736600
1992    97.779479
1993    97.779479
1994    98.545176
1995    96.133231
1996    94.601838
1997    93.185299
1998    89.471669
1999    89.548239
2000    79.402757
2001    81.929556
2002    74.617152
2003    75.267994
2004    74.119449
2005    69.754977
2006    72.205207
2007    73.009188
2008    73.124043
2009    67.993874
2010    66.385911
2011    71.133231
2012    68.185299
2013    73.545176
2014    71.018377
2015    66.232772
2016    67.151608
2017    75.880551
2018    68.836141
2019    75.689127
2020    83.958652
2021    73.889740
2022    79.173047
2023    90.543645
2024    99.004594
dtype: float64

In [20]:
cols_to_drop = [str(year) for year in range(1985, 2000)]
Financial_Hardships.drop(columns=cols_to_drop, inplace=True,errors='ignore')

In [21]:
Financial_Hardships.head(10)

,REF_AREA_LABEL,URBANIZATION_LABEL,HH_MAC_LABEL,IC_QUINTILE_LABEL,FINANCIAL_HARDSHIP,INDICATOR_LABEL,2000,2001,2002,2003,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Dominican Republic,Urban area,All types,All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,14.17,NaN,NaN,NaN,NaN,NaN,NaN
1,Serbia,Total,All types,All,PUSHED,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,0.79,0.70,1.23,0.81,0.83,NaN,0.79,1.65,NaN,NaN
2,Greece,Total,All types,All,PUSHED,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,1.69,2.08,1.34,2.11,1.53,1.74,1.87,1.34,1.97,NaN
3,Dominican Republic,Total,All types,Wealth quintile 1 (poorest),ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,57.49,NaN,NaN,NaN,NaN,NaN,NaN
4,West Bank and Gaza,Total,All types,All,LARGE,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,3.72,NaN,NaN,NaN,NaN,NaN,NaN,3.52,NaN
5,Ethiopia,Total,All types,All,FURTHER,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,22.73,NaN,NaN,18.84,NaN,NaN,22.27,NaN,NaN,NaN
6,Brazil,Total,Older adults only,All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Iraq,Total,"Adults, children, and adolescents",All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,NaN,NaN,32.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Togo,Total,Adults only,All,ALL_FH,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,...,27.98,NaN,NaN,NaN,NaN,NaN,3.49,NaN,NaN,NaN
9,Lower middle income,Total,All types,Wealth quintile 5 (richest),ALL_FH,Population facing financial hardship due to ou...,3.52,3.3,3.97,3.36,...,5.12,5.19,4.74,4.54,4.54,3.96,3.99,4.52,NaN,NaN

In [22]:
Financial_Hardships.columns

Index(['REF_AREA_LABEL', 'URBANIZATION_LABEL', 'HH_MAC_LABEL',
       'IC_QUINTILE_LABEL', 'FINANCIAL_HARDSHIP', 'INDICATOR_LABEL', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020', '2021', '2022', '2023', '2024'],
      dtype='object')

In [23]:
year_cols = [col for col in Financial_Hardships.columns if col.isdigit()]

# check how many countries you lose at 70% threshold
row_missing_pct = Financial_Hardships[year_cols].isnull().mean(axis=1) * 100

print("Before:", Financial_Hardships.shape[0], "rows")
print("Dropped:", (row_missing_pct > 70).sum(), "rows")
print("Kept:", (row_missing_pct <= 70).sum(), "rows")

Before: 2612 rows
Dropped: 1911 rows
Kept: 701 rows

In [24]:
print("Before:", Financial_Hardships.shape[0], "rows")
print("Dropped:", (row_missing_pct > 80).sum(), "rows")
print("Kept:", (row_missing_pct <= 80).sum(), "rows")

Before: 2612 rows
Dropped: 1572 rows
Kept: 1040 rows

In [25]:
Financial_Hardships = Financial_Hardships[row_missing_pct <= 80]
print("New shape:", Financial_Hardships.shape)

New shape: (1040, 31)

In [26]:
Financial_Hardships['REF_AREA_LABEL'].nunique()

81

In [27]:
# reload
Financial_Hardships = pd.read_csv("/Users/deannalakshman/Desktop/IIT/YEAR 2/SEM 2/DSPLC/Individual technical/Raw_Datasets/Finacial hardships.csv")

# drop 1985-1999 year columns
cols_to_drop = [str(year) for year in range(1985, 2000)]
Financial_Hardships.drop(columns=cols_to_drop, inplace=True, errors='ignore')

# keep only the columns you need
cols_to_keep = ['REF_AREA_LABEL', 'FINANCIAL_HARDSHIP_LABEL', 'URBANIZATION_LABEL', 
                'IC_QUINTILE_LABEL', 'INDICATOR_LABEL'] + \
               [col for col in Financial_Hardships.columns if col.isdigit()]

Financial_Hardships = Financial_Hardships[cols_to_keep]

# remove regional aggregates
regions_to_remove = [
    'East Asia & Pacific', 'Europe & Central Asia', 'World',
    'High income', 'Latin America & Caribbean', 'Low income',
    'Lower middle income', 'Middle East, North Africa, Afghanistan & Pakistan',
    'North America', 'South Asia', 'Sub-Saharan Africa', 'Upper middle income'
]
Financial_Hardships = Financial_Hardships[~Financial_Hardships['REF_AREA_LABEL'].isin(regions_to_remove)]

print(Financial_Hardships.shape)
Financial_Hardships.head()

(2492, 30)

,REF_AREA_LABEL,FINANCIAL_HARDSHIP_LABEL,URBANIZATION_LABEL,IC_QUINTILE_LABEL,INDICATOR_LABEL,2000,2001,2002,2003,2004,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Dominican Republic,All financial hardship,Urban area,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,14.17,NaN,NaN,NaN,NaN,NaN,NaN
1,Serbia,2.1: Pushed into poverty (based on societal po...,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,0.79,0.70,1.23,0.81,0.83,NaN,0.79,1.65,NaN,NaN
2,Greece,2.1: Pushed into poverty (based on societal po...,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,2.15,...,1.69,2.08,1.34,2.11,1.53,1.74,1.87,1.34,1.97,NaN
3,Dominican Republic,All financial hardship,Total,Wealth quintile 1 (poorest),Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,57.49,NaN,NaN,NaN,NaN,NaN,NaN
4,West Bank and Gaza,1: Facing large (but non-impoverishing) out-of...,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,4.12,...,NaN,3.72,NaN,NaN,NaN,NaN,NaN,NaN,3.52,NaN

In [28]:
Financial_Hardships.drop(columns=['2024'], inplace=True, errors='ignore')

In [29]:
Financial_Hardships.drop_duplicates(inplace=True)

In [30]:
fh_label_map = {
    'All financial hardship': 'All',
    '1: Facing large (but non-impoverishing) out-of-pocket health expenditure': 'Large OOP',
    '2: Facing impoverishing out-of-pocket health expenditure, based on the societal poverty line': 'Impoverishing',
    '2.1: Pushed into poverty (based on societal poverty line) due to out-of-pocket health expenditure': 'Pushed into poverty',
    '2.2: Further impoverished due to out-of-pocket health expenditure, based on the societal poverty line': 'Further impoverished'
}
Financial_Hardships['FINANCIAL_HARDSHIP_LABEL'] = Financial_Hardships['FINANCIAL_HARDSHIP_LABEL'].map(fh_label_map)

In [31]:
Health_Coverage.to_csv("Cleaned_datasets/Health_Coverage_Cleaned.csv", index=False, errors='ignore')
Financial_Hardships.to_csv("Cleaned_datasets/Financial_Hardships_Cleaned.csv", index=False, errors='ignore')

In [32]:
FH_total = Financial_Hardships[
    (Financial_Hardships['URBANIZATION_LABEL'] == 'Total') &
    (Financial_Hardships['IC_QUINTILE_LABEL'] == 'All') &
    (Financial_Hardships['FINANCIAL_HARDSHIP_LABEL'] == 'All')
]

print(FH_total.shape)
print(FH_total['REF_AREA_LABEL'].nunique())

(753, 29)
168

In [33]:
FH_total['FINANCIAL_HARDSHIP_LABEL'].unique()

array(['All'], dtype=object)

In [34]:
FH_total[FH_total.duplicated(subset=['REF_AREA_LABEL'], keep=False)].sort_values('REF_AREA_LABEL').head(20)

,REF_AREA_LABEL,FINANCIAL_HARDSHIP_LABEL,URBANIZATION_LABEL,IC_QUINTILE_LABEL,INDICATOR_LABEL,2000,2001,2002,2003,2004,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
932,Afghanistan,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,10.88,NaN,NaN,NaN,11.11,NaN,NaN,NaN
1750,Afghanistan,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,32.30,NaN,NaN,NaN,34.56,NaN,NaN,NaN
1639,Afghanistan,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27.19,NaN,NaN,NaN
2077,Afghanistan,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,15.21,NaN,NaN,NaN,25.34,NaN,NaN,NaN
2016,Afghanistan,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,35.88,NaN,NaN,NaN,39.83,NaN,NaN,NaN
1544,Afghanistan,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,31.20,NaN,NaN,NaN,33.05,NaN,NaN,NaN
988,Albania,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,9.96,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1677,Albania,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,30.21,NaN,NaN,...,NaN,NaN,NaN,14.82,NaN,NaN,NaN,NaN,NaN,NaN
2148,Albania,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,13.25,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2532,Albania,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,38.29,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
813,Albania,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,18.46,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,Albania,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,29.42,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2471,Andorra,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.83,NaN,NaN,NaN
2299,Andorra,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.38,7.65,6.17,4.36,5.58
1203,Andorra,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.74,NaN,NaN,NaN
2115,Angola,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,49.61,NaN,NaN,NaN,NaN,NaN
142,Angola,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,9.15,NaN,NaN,NaN,NaN,NaN
635,Angola,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20.93,NaN,NaN,NaN,NaN,NaN
878,Angola,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,39.53,NaN,NaN,NaN,NaN,NaN
164,Angola,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,24.02,NaN,NaN,NaN,NaN,NaN

In [36]:
HC_total = Health_Coverage[Health_Coverage['INDEX_COMP_LABEL'] == 'Full index']
print(HC_total.shape)

(195, 27)

In [37]:
print(HC_total.columns.tolist())
print(HC_total.shape)

['REF_AREA_LABEL', 'INDEX_COMP_LABEL', 'INDICATOR_LABEL', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023']
(195, 27)

In [38]:
print(Financial_Hardships.columns.tolist())
print(Financial_Hardships.shape)

['REF_AREA_LABEL', 'FINANCIAL_HARDSHIP_LABEL', 'URBANIZATION_LABEL', 'IC_QUINTILE_LABEL', 'INDICATOR_LABEL', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023']
(2488, 29)

In [39]:
year_cols_hc = [col for col in HC_total.columns if col.isdigit()]

HC_long = HC_total.melt(
    id_vars=['REF_AREA_LABEL', 'INDEX_COMP_LABEL'],
    value_vars=year_cols_hc,
    var_name='year',
    value_name='hc_coverage'
)

HC_long['year'] = HC_long['year'].astype(int)
print(HC_long.shape)

(4680, 4)

In [40]:
year_cols_fh = [col for col in Financial_Hardships.columns if col.isdigit()]

FH_long = Financial_Hardships.melt(
    id_vars=['REF_AREA_LABEL', 'FINANCIAL_HARDSHIP_LABEL', 'URBANIZATION_LABEL', 'IC_QUINTILE_LABEL'],
    value_vars=year_cols_fh,
    var_name='year',
    value_name='financial_hardship'
)

FH_long['year'] = FH_long['year'].astype(int)
print(FH_long.shape)

(59712, 6)

In [41]:
merged = pd.merge(
    HC_long,
    FH_long,
    on=['REF_AREA_LABEL', 'year'],
    how='inner'
)

print(merged.shape)
print(merged['REF_AREA_LABEL'].nunique())
merged.head()

(58848, 8)
165

,REF_AREA_LABEL,INDEX_COMP_LABEL,year,hc_coverage,FINANCIAL_HARDSHIP_LABEL,URBANIZATION_LABEL,IC_QUINTILE_LABEL,financial_hardship
0,Cambodia,Full index,2000,26.0,All,Total,All,NaN
1,Cambodia,Full index,2000,26.0,Further impoverished,Total,All,NaN
2,Cambodia,Full index,2000,26.0,All,Total,All,NaN
3,Cambodia,Full index,2000,26.0,All,Urban area,All,NaN
4,Cambodia,Full index,2000,26.0,All,Total,Wealth quintile 4,NaN

In [42]:
merged = merged.drop(columns=['INDEX_COMP_LABEL'])

merged.to_csv("Cleaned_Datasets/Health_Coverage_Financial_Hardship.csv", index=False)