In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [9]:
#load the dataset
Financial_data = pd.read_csv('Cleaned_datasets/Financial_Hardships_Cleaned.csv')
Health_data = pd.read_csv('Cleaned_datasets/Health_Coverage_Cleaned.csv')

In [10]:
os.makedirs("logs", exist_ok=True)

log_file = open("logs/EDA.txt", "a")

def log(msg):
    print(msg)
    log_file.write(msg + "\n")
    log_file.flush()  # Ensure the message is written to the file immediately

# TEST LOGS
log("Program started")
log("Datasets are loaded successfully")

Program started
Datasets are loaded successfully

## Basic overview of the datasets

In [11]:
Financial_data.shape

(2488, 29)

In [12]:
Health_data.shape

(975, 27)

In [13]:
log("Financial_Hardships dataset shape: " + str(Financial_data.shape))
log("Health_Coverage dataset shape: " + str(Health_data.shape))

Financial_Hardships dataset shape: (2488, 29)
Health_Coverage dataset shape: (975, 27)

In [14]:
Financial_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2488 entries, 0 to 2487
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   REF_AREA_LABEL            2488 non-null   object
 1   FINANCIAL_HARDSHIP_LABEL  2488 non-null   object
 2   URBANIZATION_LABEL        2488 non-null   object
 3   IC_QUINTILE_LABEL         2488 non-null   object
 4   INDICATOR_LABEL           2488 non-null   object
 5   2000                      418 non-null    float64
 6   2001                      352 non-null    float64
 7   2002                      543 non-null    float64
 8   2003                      526 non-null    float64
 9   2004                      556 non-null    float64
 10  2005                      670 non-null    float64
 11  2006                      606 non-null    float64
 12  2007                      585 non-null    float64
 13  2008                      582 non-null    float64
 14  2009                      716 non-null    float64
 15  2010                      758 non-null    float64
 16  2011                      634 non-null    float64
 17  2012                      711 non-null    float64
 18  2013                      571 non-null    float64
 19  2014                      637 non-null    float64
 20  2015                      762 non-null    float64
 21  2016                      738 non-null    float64
 22  2017                      510 non-null    float64
 23  2018                      694 non-null    float64
 24  2019                      515 non-null    float64
 25  2020                      299 non-null    float64
 26  2021                      562 non-null    float64
 27  2022                      424 non-null    float64
 28  2023                      247 non-null    float64
dtypes: float64(24), object(5)
memory usage: 563.8+ KB

In [15]:
Financial_data.head(10)

,REF_AREA_LABEL,FINANCIAL_HARDSHIP_LABEL,URBANIZATION_LABEL,IC_QUINTILE_LABEL,INDICATOR_LABEL,2000,2001,2002,2003,2004,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Dominican Republic,All,Urban area,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,14.17,NaN,NaN,NaN,NaN,NaN
1,Serbia,Pushed into poverty,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,1.24,0.79,0.70,1.23,0.81,0.83,NaN,0.79,1.65,NaN
2,Greece,Pushed into poverty,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,2.15,...,1.26,1.69,2.08,1.34,2.11,1.53,1.74,1.87,1.34,1.97
3,Dominican Republic,All,Total,Wealth quintile 1 (poorest),Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,57.49,NaN,NaN,NaN,NaN,NaN
4,West Bank and Gaza,Large OOP,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,4.12,...,NaN,NaN,3.72,NaN,NaN,NaN,NaN,NaN,NaN,3.52
5,Ethiopia,Further impoverished,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,25.92,...,NaN,22.73,NaN,NaN,18.84,NaN,NaN,22.27,NaN,NaN
6,Brazil,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Iraq,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,32.27,NaN,NaN,NaN,NaN,NaN,NaN
8,Togo,All,Total,All,Population facing financial hardship due to ou...,NaN,NaN,NaN,NaN,NaN,...,NaN,27.98,NaN,NaN,NaN,NaN,NaN,3.49,NaN,NaN
9,"Gambia, The",All,Total,Wealth quintile 4,Population facing financial hardship due to ou...,NaN,NaN,NaN,0.11,NaN,...,NaN,0.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
Health_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 975 entries, 0 to 974
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   REF_AREA_LABEL    975 non-null    object
 1   INDEX_COMP_LABEL  975 non-null    object
 2   INDICATOR_LABEL   975 non-null    object
 3   2000              975 non-null    float64
 4   2001              975 non-null    float64
 5   2002              975 non-null    float64
 6   2003              975 non-null    float64
 7   2004              975 non-null    float64
 8   2005              975 non-null    float64
 9   2006              975 non-null    float64
 10  2007              975 non-null    float64
 11  2008              975 non-null    float64
 12  2009              975 non-null    float64
 13  2010              975 non-null    float64
 14  2011              975 non-null    float64
 15  2012              975 non-null    float64
 16  2013              975 non-null    float64
 17  2014              975 non-null    float64
 18  2015              975 non-null    float64
 19  2016              975 non-null    float64
 20  2017              975 non-null    float64
 21  2018              975 non-null    float64
 22  2019              975 non-null    float64
 23  2020              975 non-null    float64
 24  2021              975 non-null    float64
 25  2022              975 non-null    float64
 26  2023              975 non-null    float64
dtypes: float64(24), object(3)
memory usage: 205.8+ KB

In [17]:
log('Health Coverage summary statistics for year columns')
year_cols_hc = [col for col in Health_data.columns if col.isdigit()]
Health_data[year_cols_hc].describe().round(2)

Health Coverage summary statistics for year columns

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
count,975.00,975.00,975.00,975.00,975.00,975.00,975.00,975.00,975.00,975.00,...,975.00,975.00,975.00,975.00,975.00,975.00,975.00,975.00,975.00,975.00
mean,57.95,58.36,58.85,59.38,59.92,60.50,61.32,62.06,62.64,63.23,...,67.21,67.64,68.01,68.46,68.12,68.53,68.97,69.09,69.60,69.73
std,24.54,24.50,24.41,24.34,24.20,23.89,23.27,22.77,22.47,22.12,...,21.03,20.85,20.78,20.35,20.18,20.20,20.04,19.94,19.78,19.61
min,2.00,2.00,2.00,2.00,2.00,2.00,4.00,6.00,6.00,5.00,...,9.00,11.00,10.00,8.00,9.00,11.00,9.00,9.00,10.00,10.00
25%,41.00,41.00,42.00,43.00,44.00,45.00,46.00,46.00,48.00,48.00,...,53.00,54.00,54.00,55.00,55.00,55.00,56.00,56.00,57.00,56.00
50%,61.00,61.00,62.00,63.00,63.00,64.00,64.00,65.00,65.00,66.00,...,69.00,69.00,70.00,70.00,69.00,70.00,70.00,71.00,71.00,71.00
75%,76.00,76.00,76.00,77.00,78.00,78.00,78.50,79.00,79.00,79.50,...,83.00,83.00,83.00,84.00,83.00,84.00,84.00,84.00,85.00,85.00
max,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,...,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00

In [19]:
log('Financial Hardships summary statistics for year columns')
year_cols_fh = [col for col in Financial_data.columns if col.isdigit()]
Financial_data[year_cols_fh].describe().round(2)

Financial Hardships summary statistics for year columns

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
count,418.00,352.00,543.00,526.00,556.00,670.00,606.00,585.00,582.00,716.00,...,637.00,762.00,738.00,510.00,694.00,515.00,299.00,562.00,424.00,247.00
mean,19.89,19.23,19.41,19.07,18.38,18.17,16.89,17.71,14.50,17.03,...,17.55,16.75,17.27,16.55,19.23,15.82,16.10,17.70,16.92,15.72
std,19.59,21.14,19.23,19.78,19.96,19.13,19.30,20.77,15.67,18.57,...,20.37,20.24,17.92,18.19,20.90,17.34,17.48,19.56,19.65,16.78
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00
25%,4.59,4.48,4.66,4.54,4.12,3.90,3.08,3.16,3.12,3.44,...,3.00,2.31,3.73,3.38,3.55,2.98,3.31,3.54,3.26,3.62
50%,13.83,11.91,14.00,13.38,12.06,12.38,10.12,10.37,9.57,11.00,...,10.10,9.54,11.30,10.48,11.76,10.23,9.90,10.34,9.46,10.47
75%,27.76,26.52,25.69,25.19,25.34,25.47,22.56,23.56,20.43,22.93,...,23.25,22.72,23.88,22.22,28.01,21.90,23.36,25.49,24.52,21.92
max,86.55,98.85,98.64,92.56,98.63,94.93,100.00,99.88,99.10,96.36,...,99.24,100.00,94.10,97.90,99.22,97.53,93.13,99.52,96.36,97.14